// 此文件由 tauri-specta 自动生成，请勿手动修改。
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  获取完整状态。窗口创建后调用一次，之后依靠事件增量更新。 */
	getSnapshot: () => typedError<AudioSnapshot, AppError>(__TAURI_INVOKE("get_snapshot")),
	setMasterVolume: (volume: number) => typedError<null, AppError>(__TAURI_INVOKE("set_master_volume", { volume })),
	setMasterMute: (muted: boolean) => typedError<null, AppError>(__TAURI_INVOKE("set_master_mute", { muted })),
	setAppVolume: (appId: string, volume: number) => typedError<null, AppError>(__TAURI_INVOKE("set_app_volume", { appId, volume })),
	setAppMute: (appId: string, muted: boolean) => typedError<null, AppError>(__TAURI_INVOKE("set_app_mute", { appId, muted })),
	/**  组音量：`apps` 为组内应用及其在组音量 100% 时的音量，按比例缩放后写入。 */
	setGroupVolume: (apps: ([string, number])[], volume: number) => typedError<null, AppError>(__TAURI_INVOKE("set_group_volume", { apps: apps.map(i=>i), volume })),
	setGroupMute: (appIds: string[], muted: boolean) => typedError<null, AppError>(__TAURI_INVOKE("set_group_mute", { appIds, muted })),
	/**  前端首次渲染完成。新建的窗口在此之后才显示，避免出现空白窗口。 */
	windowReady: () => __TAURI_INVOKE<void>("window_ready"),
	/**
	 *  前端内容高度（逻辑像素）变化时调用，窗口高度随之调整。
	 *  返回高度动画的时长（毫秒），立即完成时为 0；动画期间前端隐藏滚动条。
	 */
	fitWindowHeight: (contentHeight: number) => __TAURI_INVOKE<number>("fit_window_height", { contentHeight }),
	/**  一次系统音量调节结束（松开滑块、滚轮停止）时调用，按设置播放提示音。 */
	playVolumeFeedback: () => __TAURI_INVOKE<void>("play_volume_feedback"),
	/**  窗口所在显示器的刷新率（Hz），读取失败时为 `None`。设置页用它显示默认帧率。 */
	getRefreshRate: () => __TAURI_INVOKE<number | null>("get_refresh_rate"),
	getSettings: () => __TAURI_INVOKE<Settings_Serialize>("get_settings").then((v) => (({...v,groups:v.groups.map(i=>({...i,apps:i.apps.map(i=>i)})),scenes:v.scenes.map(i=>({...i,apps:i.apps.map(i=>i)}))}) as typeof v)),
	/**  各设置项的默认值。设置页据此判断是否显示“恢复默认”。 */
	getDefaultSettings: () => __TAURI_INVOKE<Settings_Serialize>("get_default_settings").then((v) => (({...v,groups:v.groups.map(i=>({...i,apps:i.apps.map(i=>i)})),scenes:v.scenes.map(i=>({...i,apps:i.apps.map(i=>i)}))}) as typeof v)),
	/**  保存设置并立即生效。窗口隐藏策略在下一次隐藏窗口时生效。 */
	setSettings: (settings: Settings_Deserialize) => typedError<null, AppError>(__TAURI_INVOKE("set_settings", { settings: ({...settings,groups:settings.groups?.map(i=>({...i,apps:i.apps.map(i=>i)})),scenes:settings.scenes?.map(i=>({...i,apps:i.apps.map(i=>i)}))}) })),
	/**  设置页拖动宽度滑块时预览窗口宽度（逻辑像素），不写入设置；松手后由 `set_settings` 保存。 */
	previewWindowWidth: (width: number) => __TAURI_INVOKE<void>("preview_window_width", { width }),
	/**  是否开机自启（读取系统中的实际注册状态）。 */
	getAutostart: () => __TAURI_INVOKE<boolean>("get_autostart"),
	getPinMode: () => __TAURI_INVOKE<PinMode>("get_pin_mode"),
	/**  切换窗口固定方式（标题栏图钉按钮）。 */
	setPinMode: (mode: PinMode) => __TAURI_INVOKE<void>("set_pin_mode", { mode }),
	/**  当前 Windows 强调色，之后的变化通过 `theme://accent` 事件推送。读取失败时为 `None`。 */
	getAccentColors: () => __TAURI_INVOKE<{
	light: string,
	dark: string,
} | null>("get_accent_colors"),
	setAutostart: (enabled: boolean) => typedError<null, AppError>(__TAURI_INVOKE("set_autostart", { enabled })),
	/**
	 *  点击应用行：显示它的详情浮窗，已在显示这个应用时隐藏。
	 *  `anchor_top` 为应用行上边缘相对窗口内容区的位置（逻辑像素）。
	 *  必须是异步命令：Windows 上在同步命令（主线程）中创建窗口，WebView 无法完成创建。
	 */
	toggleAppDetails: (details: AppDetails, anchorTop: number) => __TAURI_INVOKE<void>("toggle_app_details", { details, anchorTop }),
	/**  点击主窗口其他位置、列表滚动或开始拖动时隐藏详情浮窗。 */
	hideAppDetails: () => __TAURI_INVOKE<void>("hide_app_details"),
	/**  在资源管理器中打开文件所在的文件夹并选中它（详情浮窗中点击路径）。 */
	revealInFolder: (path: string) => typedError<null, AppError>(__TAURI_INVOKE("reveal_in_folder", { path })),
	/**  用默认浏览器打开网址（设置页“关于”中的链接）。 */
	openUrl: (url: string) => typedError<null, AppError>(__TAURI_INVOKE("open_url", { url })),
	/**  在资源管理器中选中设置文件；还没保存过设置（文件不存在）时打开所在文件夹。 */
	revealSettingsFile: () => typedError<null, AppError>(__TAURI_INVOKE("reveal_settings_file")),
	/**  详情浮窗首次加载时读取要显示的内容；之后的更新通过 `details://show` 事件推送。 */
	getAppDetails: () => __TAURI_INVOKE<{
	app: AppAudio,
	/**  用户起的名称。 */
	alias: string | null,
} | null>("get_app_details"),
	/**  详情浮窗渲染完成，报告内容高度（逻辑像素），后端据此定位并显示。 */
	detailsReady: (contentHeight: number) => __TAURI_INVOKE<void>("details_ready", { contentHeight }),
};

/** Events */
export const events = {
	audioAppRemove: makeEvent<AppRemoveEvent>("audio://app-remove"),
	audioAppUpsert: makeEvent<AppUpsertEvent>("audio://app-upsert"),
	audioMaster: makeEvent<MasterChangedEvent>("audio://master"),
	audioSnapshot: makeEvent<AudioSnapshotEvent>("audio://snapshot"),
	detailsShow: makeEvent<AppDetailsEvent>("details://show"),
	themeAccent: makeEvent<AccentColors>("theme://accent"),
};

/* Types */
/**  浅色、深色主题下的强调色，`#RRGGBB`。 */
export type AccentColors = {
	light: string,
	dark: string,
};

/**  重命名的应用。`name` 为原来的应用名，应用没在运行时设置页也能显示。 */
export type AppAlias = {
	appId: string,
	name: string,
	/**  用户起的名称，界面中优先显示。 */
	alias: string,
};

export type AppAudio = {
	appId: string,
	name: string,
	/**
	 *  图标来源，前端通过 `appicon` 协议加载（`convertFileSrc(icon, "appicon")`）。
	 *  无法确定来源时（如管理员权限进程）为 `None`，前端显示首字母占位。
	 */
	icon: string | null,
	/**  进程的 exe 文件名，右键菜单“复制进程名”使用。系统声音为 `None`。 */
	processName: string | null,
	/**  exe 完整路径，右键菜单“复制路径”使用。打不开进程时为 `None`。 */
	exePath: string | null,
	volume: VolumeState,
	/**  是否有会话正在播放。 */
	active: boolean,
	sessionCount: number,
};

/**  浮窗显示的内容。 */
export type AppDetails = {
	app: AppAudio,
	/**  用户起的名称。 */
	alias: string | null,
};

/**  要显示的内容变化时推送给浮窗。 */
export type AppDetailsEvent = AppDetails;

export type AppError = {
	code: ErrorCode,
	message: string,
};

/**  应用分组：组内应用在主界面合并为一行，由组音量按比例统一调节。 */
export type AppGroup = {
	/**  分组标识，创建时由前端生成，不随改名变化。 */
	id: string,
	name: string,
	apps: GroupMember[],
	/**  组音量（0–1）。组内应用的音量 = 该应用在组音量 100% 时的音量 × 组音量。 */
	volume: number,
	/**  在主界面中展开显示组内应用。 */
	expanded?: boolean,
};

/**  应用的最后一个会话退出。 */
export type AppRemoveEvent = {
	appId: string,
};

/**  应用出现或状态变化。 */
export type AppUpsertEvent = AppAudio;

export type AudioSnapshot = {
	/**  没有任何输出设备时为 `None`。 */
	device: DeviceInfo | null,
	/**  已按“活跃在前，再按名称”排序。 */
	apps: AppAudio[],
};

/**  设备切换或需要整体重建时推送完整状态。 */
export type AudioSnapshotEvent = AudioSnapshot;

export type DeviceInfo = {
	id: string,
	name: string,
	/**  设备的系统总音量。 */
	master: VolumeState,
};

export type ErrorCode = 
/**  当前没有输出设备。 */
"NoDevice" | 
/**  应用已没有音频会话（可能刚刚退出）。 */
"AppNotFound" | 
/**  Windows 音频接口调用失败。 */
"ComFailure" | 
/**  音频线程未运行。 */
"AudioThreadDown" | 
/**  设置文件读写失败。 */
"ConfigFailure" | 
/**  调用资源管理器等系统界面失败（如打开文件所在的文件夹）。 */
"ShellFailure";

/**  分组中的一个应用。 */
export type GroupMember = {
	appId: string,
	name: string,
	/**  该应用在组音量 100% 时的音量（0–1）。实际音量 = 此值 × 组音量。 */
	fullVolume: number,
};

/**  系统总音量被外部修改。 */
export type MasterChangedEvent = VolumeState;

/**  窗口固定方式，由标题栏的图钉按钮切换，只在本次运行中保持。 */
export type PinMode = 
/**  弹出面板：失焦自动隐藏，保持在最前。 */
"normal" | 
/**  定住：失焦不隐藏，可被其他窗口遮挡。 */
"pinned" | 
/**  定住并置顶：失焦不隐藏，始终在最前。 */
"pinnedOnTop";

/**  置顶或隐藏的应用。记下名称，应用没在运行时也能在设置页中显示。 */
export type SavedApp = {
	appId: string,
	name: string,
};

/**  音量场景：一组应用的音量组合，一键切换（如“游戏”“会议”“音乐”）。 */
export type Scene = {
	/**  场景标识，创建时由前端生成，不随改名变化。 */
	id: string,
	name: string,
	apps: SceneApp[],
};

/**  场景中一个应用的音量。 */
export type SceneApp = {
	appId: string,
	name: string,
	/**  音量（0–1）。 */
	volume: number,
	muted: boolean,
};

export type Settings = Settings_Serialize | Settings_Deserialize;

export type Settings_Deserialize = {
	windowPolicy?: WindowPolicy_Deserialize,
	/**  智能模式下，窗口隐藏多少秒后释放界面。 */
	smartReleaseSeconds?: number,
	/**  调节系统音量后播放提示音。 */
	volumeFeedback?: boolean,
	/**  在主界面显示调试工具（添加占位应用）。 */
	debugTools?: boolean,
	/**  窗口滑入 / 滑出动画的帧率（帧 / 秒）。`None` 表示跟随显示器刷新率。 */
	animationFps?: number | null,
	/**  窗口宽度（逻辑像素）。 */
	windowWidth?: number,
	/**  系统音量放在应用列表下方（靠近任务栏），默认开启。 */
	masterAtBottom?: boolean,
	/**  应用列表倒序：活跃应用排在底部，更靠近任务栏。默认开启。 */
	appsReversed?: boolean,
	/**  标题栏显示“固定窗口”按钮。 */
	showPinButton?: boolean,
	/**  标题栏显示“新建分组”按钮。 */
	showGroupButton?: boolean,
	/**  标题栏显示“保存为场景”按钮。 */
	showSceneButton?: boolean,
	/**
	 *  界面使用 GPU 渲染，默认开启。关闭时窗口显示期间少占约 70 MB 内存（实测见
	 *  docs/architecture.md），界面简单，软件渲染也足够流畅。重启程序后生效。
	 */
	hardwareAcceleration?: boolean,
	theme?: ThemeMode,
	/**  强调色 `#RRGGBB`；`None` 表示跟随 Windows 强调色。 */
	accent?: string | null,
	/**  置顶的应用，按显示顺序排列（可拖拽调整）。 */
	pinnedApps?: SavedApp[],
	/**  隐藏的应用。 */
	hiddenApps?: SavedApp[],
	/**  应用分组，按显示顺序排列。一个应用只属于一个分组。 */
	groups?: AppGroup[],
	/**  重命名的应用。 */
	appAliases?: AppAlias[],
	/**  音量场景，按显示顺序排列。 */
	scenes?: Scene[],
	trayStyle?: TrayStyle,
	/**  在任务栏任意位置滚动滚轮调节系统音量（默认只在托盘图标上）。 */
	taskbarWheel?: boolean,
	/**  托盘 / 任务栏滚轮每格调节的百分点（1–10）。 */
	wheelStep?: number,
	/**  托盘 / 任务栏滚轮停止后播放提示音。 */
	wheelFeedback?: boolean,
	/**  托盘 / 任务栏滚轮调节时显示 Windows 自带的音量浮层。 */
	wheelOsd?: boolean,
	/**  托盘图标颜色 `#RRGGBB`；`None` 表示跟随任务栏深浅色（深色任务栏为白色，浅色为黑色）。 */
	trayColor?: string | null,
	/**  还没询问过是否开机自启：首次运行时为 `true`，主界面据此弹出询问，回答后清除。 */
	autostartPrompt?: boolean,
};

export type Settings_Serialize = {
	windowPolicy: WindowPolicy_Serialize,
	/**  智能模式下，窗口隐藏多少秒后释放界面。 */
	smartReleaseSeconds: number,
	/**  调节系统音量后播放提示音。 */
	volumeFeedback: boolean,
	/**  在主界面显示调试工具（添加占位应用）。 */
	debugTools: boolean,
	/**  窗口滑入 / 滑出动画的帧率（帧 / 秒）。`None` 表示跟随显示器刷新率。 */
	animationFps: number | null,
	/**  窗口宽度（逻辑像素）。 */
	windowWidth: number,
	/**  系统音量放在应用列表下方（靠近任务栏），默认开启。 */
	masterAtBottom: boolean,
	/**  应用列表倒序：活跃应用排在底部，更靠近任务栏。默认开启。 */
	appsReversed: boolean,
	/**  标题栏显示“固定窗口”按钮。 */
	showPinButton: boolean,
	/**  标题栏显示“新建分组”按钮。 */
	showGroupButton: boolean,
	/**  标题栏显示“保存为场景”按钮。 */
	showSceneButton: boolean,
	/**
	 *  界面使用 GPU 渲染，默认开启。关闭时窗口显示期间少占约 70 MB 内存（实测见
	 *  docs/architecture.md），界面简单，软件渲染也足够流畅。重启程序后生效。
	 */
	hardwareAcceleration: boolean,
	theme: ThemeMode,
	/**  强调色 `#RRGGBB`；`None` 表示跟随 Windows 强调色。 */
	accent: string | null,
	/**  置顶的应用，按显示顺序排列（可拖拽调整）。 */
	pinnedApps: SavedApp[],
	/**  隐藏的应用。 */
	hiddenApps: SavedApp[],
	/**  应用分组，按显示顺序排列。一个应用只属于一个分组。 */
	groups: AppGroup[],
	/**  重命名的应用。 */
	appAliases: AppAlias[],
	/**  音量场景，按显示顺序排列。 */
	scenes: Scene[],
	trayStyle: TrayStyle,
	/**  在任务栏任意位置滚动滚轮调节系统音量（默认只在托盘图标上）。 */
	taskbarWheel: boolean,
	/**  托盘 / 任务栏滚轮每格调节的百分点（1–10）。 */
	wheelStep: number,
	/**  托盘 / 任务栏滚轮停止后播放提示音。 */
	wheelFeedback: boolean,
	/**  托盘 / 任务栏滚轮调节时显示 Windows 自带的音量浮层。 */
	wheelOsd: boolean,
	/**  托盘图标颜色 `#RRGGBB`；`None` 表示跟随任务栏深浅色（深色任务栏为白色，浅色为黑色）。 */
	trayColor: string | null,
	/**  还没询问过是否开机自启：首次运行时为 `true`，主界面据此弹出询问，回答后清除。 */
	autostartPrompt: boolean,
};

/**  界面深浅色。 */
export type ThemeMode = 
/**  跟随 Windows 的“应用模式”。 */
"system" | "light" | "dark";

/**  托盘图标样式，见 `tray/glyph.rs`。 */
export type TrayStyle = 
/**  与 Windows 自带的音量图标一致，随音量分档变化。 */
"speaker" | "headphones" | 
/**  音符。 */
"note" | 
/**  显示音量数字。 */
"number";

export type VolumeState = {
	volume: number,
	muted: boolean,
};

/**  窗口隐藏后的运行模式。实测数据见 docs/architecture.md“决策记录”。 */
export type WindowPolicy = WindowPolicy_Serialize | WindowPolicy_Deserialize;

/**  窗口隐藏后的运行模式。实测数据见 docs/architecture.md“决策记录”。 */
export type WindowPolicy_Deserialize = 
/**  常驻：只隐藏窗口。打开约 20 ms，常驻内存约 195 MB。 */
"resident" | 
/**  常驻：只隐藏窗口。打开约 20 ms，常驻内存约 195 MB。 */
"keep" | 
/**  静默：隐藏即释放界面。打开约 0.55 秒，常驻内存约 3 MB。 */
"silent" | 
/**  静默：隐藏即释放界面。打开约 0.55 秒，常驻内存约 3 MB。 */
"destroy" | 
/**  智能：隐藏后保留界面，连续 `smart_release_seconds` 秒未打开才释放。 */
"smart";

/**  窗口隐藏后的运行模式。实测数据见 docs/architecture.md“决策记录”。 */
export type WindowPolicy_Serialize = 
/**  常驻：只隐藏窗口。打开约 20 ms，常驻内存约 195 MB。 */
"resident" | 
/**  静默：隐藏即释放界面。打开约 0.55 秒，常驻内存约 3 MB。 */
"silent" | 
/**  智能：隐藏后保留界面，连续 `smart_release_seconds` 秒未打开才释放。 */
"smart";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

