// 此文件由 tauri-specta 自动生成，请勿手动修改。
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  获取完整状态。窗口创建后调用一次，之后依靠事件增量更新。 */
	getSnapshot: () => typedError<AudioSnapshot, AppError>(__TAURI_INVOKE("get_snapshot")),
	setMasterVolume: (volume: number) => typedError<null, AppError>(__TAURI_INVOKE("set_master_volume", { volume })),
	setMasterMute: (muted: boolean) => typedError<null, AppError>(__TAURI_INVOKE("set_master_mute", { muted })),
	setAppVolume: (appId: string, volume: number) => typedError<null, AppError>(__TAURI_INVOKE("set_app_volume", { appId, volume })),
	setAppMute: (appId: string, muted: boolean) => typedError<null, AppError>(__TAURI_INVOKE("set_app_mute", { appId, muted })),
	/**  前端首次渲染完成。新建的窗口在此之后才显示，避免出现空白窗口。 */
	windowReady: () => __TAURI_INVOKE<void>("window_ready"),
	/**  前端内容高度（逻辑像素）变化时调用，窗口高度随之调整。 */
	fitWindowHeight: (contentHeight: number) => __TAURI_INVOKE<void>("fit_window_height", { contentHeight }),
	getSettings: () => __TAURI_INVOKE<Settings_Serialize>("get_settings"),
	/**  保存设置并立即生效。窗口隐藏策略在下一次隐藏窗口时生效。 */
	setSettings: (settings: Settings_Deserialize) => typedError<null, AppError>(__TAURI_INVOKE("set_settings", { settings })),
};

/** Events */
export const events = {
	audioAppRemove: makeEvent<AppRemoveEvent>("audio://app-remove"),
	audioAppUpsert: makeEvent<AppUpsertEvent>("audio://app-upsert"),
	audioMaster: makeEvent<MasterChangedEvent>("audio://master"),
	audioSnapshot: makeEvent<AudioSnapshotEvent>("audio://snapshot"),
};

/* Types */
export type AppAudio = {
	appId: string,
	name: string,
	/**  `data:` URL，暂未实现图标提取，恒为 `None`。 */
	icon: string | null,
	volume: VolumeState,
	/**  是否有会话正在播放。 */
	active: boolean,
	sessionCount: number,
};

export type AppError = {
	code: ErrorCode,
	message: string,
};

/**  应用的最后一个会话退出。 */
export type AppRemoveEvent = {
	appId: string,
};

/**  应用出现或状态变化。 */
export type AppUpsertEvent = AppAudio;

export type AudioSnapshot = {
	/**  没有任何输出设备时为 `None`。 */
	device: DeviceInfo | null,
	/**  已按“活跃在前，再按名称”排序。 */
	apps: AppAudio[],
};

/**  设备切换或需要整体重建时推送完整状态。 */
export type AudioSnapshotEvent = AudioSnapshot;

export type DeviceInfo = {
	id: string,
	name: string,
	/**  设备的系统总音量。 */
	master: VolumeState,
};

export type ErrorCode = 
/**  当前没有输出设备。 */
"NoDevice" | 
/**  应用已没有音频会话（可能刚刚退出）。 */
"AppNotFound" | 
/**  Windows 音频接口调用失败。 */
"ComFailure" | 
/**  音频线程未运行。 */
"AudioThreadDown" | 
/**  设置文件读写失败。 */
"ConfigFailure";

/**  系统总音量被外部修改。 */
export type MasterChangedEvent = VolumeState;

export type Settings = Settings_Serialize | Settings_Deserialize;

export type Settings_Deserialize = {
	windowPolicy?: WindowPolicy_Deserialize,
	/**  智能模式下，窗口隐藏多少秒后释放界面。 */
	smartReleaseSeconds?: number,
};

export type Settings_Serialize = {
	windowPolicy: WindowPolicy_Serialize,
	/**  智能模式下，窗口隐藏多少秒后释放界面。 */
	smartReleaseSeconds: number,
};

export type VolumeState = {
	volume: number,
	muted: boolean,
};

/**  窗口隐藏后的运行模式。实测数据见 docs/architecture.md“决策记录”。 */
export type WindowPolicy = WindowPolicy_Serialize | WindowPolicy_Deserialize;

/**  窗口隐藏后的运行模式。实测数据见 docs/architecture.md“决策记录”。 */
export type WindowPolicy_Deserialize = 
/**  常驻：只隐藏窗口。打开约 20 ms，常驻内存约 195 MB。 */
"resident" | 
/**  常驻：只隐藏窗口。打开约 20 ms，常驻内存约 195 MB。 */
"keep" | 
/**  静默：隐藏即释放界面。打开约 0.55 秒，常驻内存约 3 MB。 */
"silent" | 
/**  静默：隐藏即释放界面。打开约 0.55 秒，常驻内存约 3 MB。 */
"destroy" | 
/**  智能：隐藏后保留界面，连续 `smart_release_seconds` 秒未打开才释放。 */
"smart";

/**  窗口隐藏后的运行模式。实测数据见 docs/architecture.md“决策记录”。 */
export type WindowPolicy_Serialize = 
/**  常驻：只隐藏窗口。打开约 20 ms，常驻内存约 195 MB。 */
"resident" | 
/**  静默：隐藏即释放界面。打开约 0.55 秒，常驻内存约 3 MB。 */
"silent" | 
/**  智能：隐藏后保留界面，连续 `smart_release_seconds` 秒未打开才释放。 */
"smart";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

